// <auto-generated />
using HubCollege.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubCollege.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018160939_AtualizaFormsActivity")]
    partial class AtualizaFormsActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HubCollege.model.FormsActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("questionOne")
                        .HasColumnType("longtext");

                    b.Property<string>("questionTwo")
                        .HasColumnType("longtext");

                    b.Property<string>("registrationNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormsActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
