// <auto-generated />
using System;
using HubCollege.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HubCollege.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251110003405_NewClasses")]
    partial class NewClasses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HubCollege.model.Courses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseDetail")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseDuration")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ModuleNameId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityModules")
                        .HasColumnType("int");

                    b.Property<int?>("StudentNameId")
                        .HasColumnType("int");

                    b.Property<int?>("TeacherNameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleNameId");

                    b.HasIndex("StudentNameId");

                    b.HasIndex("TeacherNameId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("HubCollege.model.FormsActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("questionOne")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("questionTwo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FormsActivities");
                });

            modelBuilder.Entity("HubCollege.model.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("HubCollege.model.Modules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassesQuantity")
                        .HasColumnType("int");

                    b.Property<string>("ModuleAbbreviation")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleDuration")
                        .HasColumnType("longtext");

                    b.Property<string>("ModuleName")
                        .HasColumnType("longtext");

                    b.Property<int?>("TeacherIdId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherIdId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("HubCollege.model.Perfil.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .HasColumnType("longtext");

                    b.Property<int>("PermissionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("HubCollege.model.Students", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ModuleNameId")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("StudentCourse")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentName")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("StudentRegistration")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ModuleNameId");

                    b.HasIndex("PermissionLevelId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("HubCollege.model.Teachers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeacherCourseAt")
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherModules")
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherName")
                        .HasColumnType("longtext");

                    b.Property<string>("TeacherRegistrationNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("HubCollege.model.Courses", b =>
                {
                    b.HasOne("HubCollege.model.Modules", "ModuleName")
                        .WithMany()
                        .HasForeignKey("ModuleNameId");

                    b.HasOne("HubCollege.model.Students", "StudentName")
                        .WithMany()
                        .HasForeignKey("StudentNameId");

                    b.HasOne("HubCollege.model.Teachers", "TeacherName")
                        .WithMany()
                        .HasForeignKey("TeacherNameId");

                    b.Navigation("ModuleName");

                    b.Navigation("StudentName");

                    b.Navigation("TeacherName");
                });

            modelBuilder.Entity("HubCollege.model.Modules", b =>
                {
                    b.HasOne("HubCollege.model.Teachers", "TeacherId")
                        .WithMany()
                        .HasForeignKey("TeacherIdId");

                    b.Navigation("TeacherId");
                });

            modelBuilder.Entity("HubCollege.model.Students", b =>
                {
                    b.HasOne("HubCollege.model.Modules", "ModuleName")
                        .WithMany()
                        .HasForeignKey("ModuleNameId");

                    b.HasOne("HubCollege.model.Perfil.Permission", "PermissionLevel")
                        .WithMany()
                        .HasForeignKey("PermissionLevelId");

                    b.Navigation("ModuleName");

                    b.Navigation("PermissionLevel");
                });
#pragma warning restore 612, 618
        }
    }
}
